name: flutter_makzan_ecommerce
description: A new Flutter setup application for starting a project.

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  adobe_xd: ^2.0.1
  carousel_slider: ^4.0.0-nullsafety.0
  connectivity: ^3.0.3
  country_code_picker: ^2.0.2
  country_currency_pickers: ^2.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0-prev2
  dropdown_search: ^5.0.3
  fancy_bottom_navigation: ^0.3.3
  firebase_core: ^1.7.0
  firebase_messaging: ^11.2.6
  flutter:
    sdk: flutter
  flutter_downloader: ^1.8.0+1
  flutter_facebook_auth: ^4.4.1+1
  flutter_google_places: ^0.3.0
  flutter_html: ^3.0.0-alpha.3
  flutter_html_table: ^3.0.0-alpha.3
  flutter_inappwebview: ^5.7.2+3
  flutter_local_notifications: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  flutter_staggered_grid_view: ^0.4.1
  flutter_svg: ^1.0.3
  flutter_typeahead: ^4.0.0
  flutter_widget_from_html: ^0.8.5
  flutter_widget_from_html_core: ^0.8.5+3
  fluttertoast: ^8.0.9
  freezed: ^2.0.3+1
  geocoding: ^2.0.0
  geolocator: ^8.2.0
  get_it: ^7.2.0
  google_maps_flutter: ^2.0.3
  google_sign_in: ^5.1.0
  http: ^0.13.1
  image_picker: ^0.8.4+8
  marquee: ^2.2.1
  package_info: ^2.0.0
  path_provider: ^2.0.1
  permission_handler: ^10.0.0
  phone_number: ^0.12.0+1
  photo_view: ^0.14.0
  pin_code_fields: ^7.0.0
  provider: ^6.0.3
  share: ^2.0.1
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0-nullsafety.0
  url_launcher: ^6.0.2
  webview_flutter: ^3.0.0

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 600
